###################################################################################
#                    OPTIONS for Image Encodings
###################################################################################

dataset_dir: "F:/AI-REAL/DataSet2/datasetfull/"  # Path to the dataset directory
encodings_dir: "F:/AI-REAL/encodings"   # Path where encoded files will be saved
project_directory: "F:/AI-REAL/"
results_path: "F:/AI-REAL/Results"

batch_size: 32                            # Batch size for processing
local_model_dir: "pretrained_models"  # Path to store pretrained model weights

# List of all pre-trained models
available_models:
  - alexnet
  - resnet18
  - resnet34
  - resnet50
  - resnet101
  - resnet152
  - resnext50_32x4d
  - resnext101_32x8d
  - wide_resnet50_2
  - wide_resnet101_2
  - vgg11
  - vgg13
  - vgg16
  - vgg19
  - convnext_tiny
  - convnext_small
  - convnext_base
  - convnext_large
  - efficientnet_b0
  - efficientnet_b1
  - efficientnet_b2
  - efficientnet_b3
  - efficientnet_b4
  - efficientnet_b5
  - efficientnet_b6
  - efficientnet_b7
  - efficientnet_v2_s
  - efficientnet_v2_m
  - efficientnet_v2_l
  - inception_v3
  - googlenet
  - mnasnet0_5
  - mnasnet0_75
  - mnasnet1_0
  - mnasnet1_3
  - mobilenet_v2
  - mobilenet_v3_large
  - mobilenet_v3_small
  - densenet121
  - densenet169
  - densenet201
  - densenet161
  - shufflenet_v2_x0_5
  - shufflenet_v2_x1_0
  - shufflenet_v2_x1_5
  - shufflenet_v2_x2_0
  - regnet_y_400mf
  - regnet_y_800mf
  - regnet_y_1_6gf
  - regnet_y_3_2gf
  - regnet_y_8gf
  - regnet_y_16gf
  - regnet_y_32gf
  - regnet_x_400mf
  - regnet_x_800mf
  - regnet_x_1_6gf
  - regnet_x_3_2gf
  - regnet_x_8gf
  - regnet_x_16gf
  - regnet_x_32gf
# List of excluded models
excluded_models:
  - squeezenet1_0
  - squeezenet1_1

###################################################################################
#                    OPTIONS for Classification
###################################################################################
svm_kernel: "linear"
n_splits: 5
